services:
  frontend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - .:/app:cached
        - /app/node_modules
      working_dir: /app
      command:  npm run dev -- --host 0.0.0.0
